# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

default_platform(:ios)

platform :ios do
  
  desc "Lint the source code based on cocoapods version"
  lane :lint do
    cocoapods(use_bundle_exec: true, repo_update: true, ansi: true)
    swiftlint(executable: "./Pods/SwiftLint/swiftlint")
  end
  
  desc "Unit testing the app"
  lane :unit_test do
    cocoapods(use_bundle_exec: true, repo_update: true, ansi: true)
    run_tests(scheme: "CookEat", device: "iPhone 8")
  end
end
